### ISSUE TITLE
add_with_ids is not implemented for Flat indexes

### ISSUE THREAD

**Issue by RomainLaby** [criteo/autofaiss#125]
Hello, I'm encountering an issue using autofaiss with flat indexes. 
`build_index` raises an error (in my case, when embeddings are ndarray, I did not test with parquet embeddings) in distributed mode, for flat indexes. This error could be related to https://github.com/facebookresearch/faiss/issues/1212 (method index.add_with_ids is not implemented for flat indexes).

```import numpy as np
from autofaiss import build_index

build_index(
    embeddings=np.ones((100, 512)),
    distributed="pyspark",
    should_be_memory_mappable=True,
    index_path="hdfs://root/user/foo/knn.index",
    index_key="Flat",
    nb_cores=20,
    max_index_memory_usage="32G",
    current_memory_available="48G",
    ids_path="hdfs://root/user/foo/test_indexing_out/ids",
    temporary_indices_folder="hdfs://root/user/foo/indices/tmp/",
    nb_indices_to_keep=5,
    index_infos_path="hdfs://root/user/r.laby/test_indexing_out/index_infos.json",
)
```

raises

`RuntimeError: Error in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const idx_t*) at /project/faiss/faiss/Index.cpp:39: add_with_ids not implemented for this type of index
`

Is it expected ? Or could this be fixed ?
Thanks !

**Comment by rom1504** [comment]
You can use key IVF1,Flat instead which supports add_with_ids and is a flat index (IVF with one cluster is the same as flat)
That's what autofaiss does when you don't force the index key

**Comment by RomainLaby** [comment]
Perfect, thanks for your answer Romain ^^
