### ISSUE TITLE
Does `avg_search_speed_ms` report search speed using only 1 core?

### ISSUE THREAD

**Issue by ZenBel** [criteo/autofaiss#150]
Hello,

By inspecting the code it seems that the option `omp_thread` in `compute_fast_metrics` is not used by `build_index`, so `avg_search_speed_ms` should report the avg search speed when using only 1 core. Is this correct?

Thanks,

Z

**Comment by hitchhicker** [comment]
Hello,

If I understand correctly, it depends on how many `nb_cores` you use for `build_index`, the number of OpenMP threads used by faiss is setup at the begining of `build_index`, see [here](https://github.com/criteo/autofaiss/blob/d5f1e210e7004859cbaf371d6a8e74e944482659/autofaiss/external/quantize.py#L191-L194). If `nb_cores` is not given, all the cores are used. Thus, the value reported in `avg_search_speed_ms` is measured accordingly.

**Comment by ZenBel** [comment]
Hi,

thanks for replying.

> If I understand correctly, it depends on how many nb_cores you use for build_index

Right, but `compute_fast_metrics` explicitly requires `omp_threads` as an [argument](https://github.com/criteo/autofaiss/blob/d5f1e210e7004859cbaf371d6a8e74e944482659/autofaiss/external/scores.py#L21) otherwise it sets `omp_threads` to `None` and [uses only 1 core](https://github.com/criteo/autofaiss/blob/d5f1e210e7004859cbaf371d6a8e74e944482659/autofaiss/external/scores.py#L37) to compute the avg speed. I could not find anywhere in the code the point where `omp_threads` is passed to `compute_fast_metrics`, hence the question.

**Comment by hitchhicker** [comment]
From [these few lines of codes](https://github.com/criteo/autofaiss/blob/d5f1e210e7004859cbaf371d6a8e74e944482659/autofaiss/external/scores.py#L36-L40), if the `omp_threads` is `None` (default to `None`), the number of threads used by faiss would not be changed. So it is not only 1 core.

**Comment by ZenBel** [comment]
You are completely right. But then why `faiss.omp_set_num_threads(1)` right before `search_speed_test` if `omp_threads` is not `None` ?

**Comment by hitchhicker** [comment]
Good question, I don't know the answer for this.

**Comment by rom1504** [comment]
The (initially) intended usage of this speed estimate is 1 core. Provided
num_cores should be the total number of cores of the machines. The function
set the number of cores to 1 , compute the speed then set back the number
of cores to the initial number

Depending on your use case you may want to compute speed for multiple cores
indeed

**Comment by ZenBel** [comment]
thanks for clarifying this. Maybe it's worth adding this info in the logger output.

Best,

Z
