### ISSUE TITLE
How does add_with_ids work in autofaiss to return IDs when searching

### ISSUE THREAD

**Issue by davidgibsonp** [criteo/autofaiss#153]
I am trying to build an index that will return the distance and the id (not index) when I run `index.search(x, k)`. From the [2.13.0](https://github.com/criteo/autofaiss/blob/master/CHANGELOG.md#2130---2022-03-09) release I see that `index.add_with_ids` was added, but whenever I load my trained index it still returns the index. I suspect I am not building it correctly but can't find any examples of how to do it.

**Current implementation** 

```python
# build
_, index_infos = build_index(
    embeddings="/embeddings",
    embedding_column_name="embedding",
    file_format="parquet",
    ids_path="/embeddings-ids",
    id_columns=["id"],
    index_path="/faiss-index",
    index_infos_path="/faiss-index-infos",
    distributed="pyspark",
)

# read
trained_index = faiss.read_index(index_infos["index_path"])

# search but returns the index not ids
trained_index.search(x, 2)
```

**What I tried**

- Set `distributed=None`
- Set `index_key="IVF1,Flat"` as mentioned in #125

Any guidance is greatly appreciated, thank you!

**Comment by hitchhicker** [comment]
Hello!

If you want to get the ids that are in the column `id` of your parquet files, you should have a look on the outputs under the `ids_path`, i.e. `"embeddings-ids"` in your example.

There, you will find a set of parquets files containing two columns: `id`  and `i`,
where:
`i` is the vector index (ranging from 0 to N-1) and `id` comes from the column `id` of your embedding parquet files. (`"embedding"`)
Thus,  it gives a mapping from vector index `i` to `id`.

What `trained_index.search` returns is the values of `i`.

Please let me know if it is still not clear for you.

**Comment by davidgibsonp** [comment]
Thanks for the explanation. Yes, that makes sense and is what I am currently doing (reading the parquet file in `ids_path` and then joining the search results on `i` to get the `id`).

I am coming from using base Faiss where I have done the following. But it sounds like the workflow, where the trained model natively returns the ids, is not supported. Is that correct?

```python
index = faiss.IndexIDMap2(faiss.IndexFlatL2(768))
index.add_with_ids(embeddings, ids)
dis, id = index.search(x, 2)
```

**Comment by hitchhicker** [comment]
It is also possible.
```
import faiss
import numpy as np

index = faiss.IndexIDMap2(faiss.IndexFlatL2(2))
embeddings = np.asarray([[1,1],[2,2]], dtype=np.float32)
ids = np.asarray([777,888])
index.add_with_ids(embeddings, ids)
index.search(np.asarray([[1,1.1]], np.float32), 1)[1]
# You would get array([[777]])
```

**Comment by davidgibsonp** [comment]
Yes that is with base faiss. But can this be done with an index trained with autofaiss, to skip the post-processing join to get ids from i?

**Comment by hitchhicker** [comment]
No, it is not supported.

**Comment by davidgibsonp** [comment]
Got it, thanks for the help!
