### ISSUE TITLE
Support building binary vector index using Hamming distance?

### ISSUE THREAD

**Issue by yzou2** [criteo/autofaiss#154]
Thanks for providing the great tool!

Does current autofaiss support automatically build binary vector indexes given pre-computed bit vectors? A use case is dedup with pre-computed hash codes.

**Comment by yzou2** [comment]
Just realized Hamming distance should be equal to the squared Euclidean distance for bit vectors. So I think we can just set the metric_type to be Euclidean for building binary index

**Comment by yzou2** [comment]
I have tested using autofaiss to build binary index, but it get errors

Command:

```
from autofaiss import build_index
import numpy as np

embeddings = np.uint8(np.random.rand(100, 512))
index, index_infos = build_index(embeddings, save_on_disk=False)
```

Error:

2023-02-07 22:42:26,581 [INFO]: Using 4 omp threads (processes), consider increasing --nb_cores if you have more
2023-02-07 22:42:26,582 [INFO]: Launching the whole pipeline 02/07/2023, 22:42:26
2023-02-07 22:42:26,582 [INFO]: Reading total number of vectors and dimension 02/07/2023, 22:42:26
  0%|                                                                                                                                          | 0/1 [00:00<?, ?it/s]
2023-02-07 22:42:26,702 [INFO]: >>> Finished "Reading total number of vectors and dimension" in 0.1197 secs
2023-02-07 22:42:26,702 [INFO]: >>> Finished "Launching the whole pipeline" in 0.1200 secs
Traceback (most recent call last):
  File "/opt/conda/envs/dedup/lib/python3.7/site-packages/embedding_reader/numpy_reader.py", line 39, in file_to_header
    return (None, [filename, *read_numpy_header(f)])
  File "/opt/conda/envs/dedup/lib/python3.7/site-packages/embedding_reader/numpy_reader.py", line 29, in read_numpy_header
    dtype = re.search(r"'descr': '([<f0-9]+)'", str(first_line)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/dedup/lib/python3.7/site-packages/autofaiss/external/quantize.py", line 209, in build_index
    meta_columns=id_columns,
  File "/opt/conda/envs/dedup/lib/python3.7/site-packages/embedding_reader/embedding_reader.py", line 20, in __init__
    self.reader = NumpyReader(embeddings_folder)
  File "/opt/conda/envs/dedup/lib/python3.7/site-packages/embedding_reader/numpy_reader.py", line 69, in __init__
    headers = get_numpy_headers(embeddings_file_paths, self.fs)
  File "/opt/conda/envs/dedup/lib/python3.7/site-packages/embedding_reader/numpy_reader.py", line 53, in get_numpy_headers
    raise Exception(f"failed reading file {c[0]}") from err
Exception: failed reading file /tmp/tmpbdsd87fd/emb.npy
```

Any suggestions to fix this?

**Comment by hitchhicker** [comment]
Hello, 

The above bug is due to the fact that embedding_reader does not support reading unit8 typing, see [this line](https://github.com/rom1504/embedding-reader/blob/main/embedding_reader/numpy_reader.py#L29). A quick workaround is to convert your binary vectors to float type.

**Comment by yzou2** [comment]
Thanks for the help! After converting uint8 vectors to float vectors, it works. 

But I have another question when I want to set "index_key" to be binary index as I assume the binary index can save lots of space and increase speed. However, from the [faiss index factory](https://github.com/facebookresearch/faiss/wiki/The-index-factory), looks like there String ID corresponds to binary index. Do you know if there are some ways in `autofaiss` to control the index type to be binary index?

**Comment by hitchhicker** [comment]
You can pass the argument `index_key` to the function `build_index` to control the index type, it  should be a string value supported by the index factory. 
`autofaiss` does not generate automatically binary index if the `index_key` is not given.

**Comment by yzou2** [comment]
I have tested it with `autofaiss` by setting `index_key` to the strings of the binary index (e.g. `BHNSW16`, or `BFlat` from the [doc](https://github.com/facebookresearch/faiss/wiki/Binary-indexes)) 

Such as the follows:
`index, index_infos = build_index(embed_array, save_on_disk=False, index_key='BFlat')`

But it raised an error message:

`RuntimeError: Error in std::unique_ptr<faiss::Index> faiss::{anonymous}::index_factory_sub(int, std::string, faiss::MetricType) at /project/faiss/faiss/index_factory.cpp:879: could not parse index string BFlat`

Is the there another arg I can use to set the output index to be the binary index, or such functionality is not supported in `autofaiss`?

**Comment by hitchhicker** [comment]
Can you try to use faiss alone with the BFlat and check the version of your faiss, to see if it is supported by that version ?

**Comment by yzou2** [comment]
My `faiss` version is the latest `1.7.3`. Moreover, I have successfully tested with `index = faiss.index_binary_factory(128, "BFlat")` without error. But `index = faiss.index_factory(128, "BFlat")` cannot be computed and will raise the error: 

`RuntimeError: Error in std::unique_ptr<faiss::Index> faiss::{anonymous}::index_factory_sub(int, std::string, faiss::MetricType) at /project/faiss/faiss/index_factory.cpp:879: could not parse index string BFlat`

**Comment by hitchhicker** [comment]
Okay, that means autofaiss does not support binary index building because it uses `index_factory` for now. :(
