### ISSUE TITLE
What is the optimized way for Bulk Retrieval of Approximate Nearest Neighbors from Large 'autofaiss' Index"

### ISSUE THREAD

**Issue by ivishalanand** [criteo/autofaiss#170]
I'm trying to understand the best way to perform a bulk retrieval of data from an index that I've created using  'autofaiss'. The index I'm dealing with is large, comprising around **8 million rows each having a dimensionality of 512.** I have been successfully constructing this index using a parquet file, and 'autofaiss' has been efficient in this process.

**However, the problem I'm encountering involves retrieving data from this index. In particular, I'm interested in retrieving the top 20 Approximate Nearest Neighbor (ANN) indices corresponding to a substantial batch of query vectors—around 250,000 vectors**  in total.

The only data I have at my disposal is stored in parquet format. What I've tried to do so far is to convert these query vectors into a npy format, and then retrieve the required data. But, it is apparent to me that this is not an optimized way to go about this task, due to various inefficiencies that are cropping up ( specially creating a npy array of 250k vectors with 512 dim embeddings

Given this situation, I'm looking for a more effective and efficient method to accomplish this task. I'm open to all suggestions and I'm particularly interested in understanding if there is a way to perform this operation directly from the parquet data I have at hand, bypassing the need to convert the data to a npy  format before querying. I appreciate your expert advice on how to proceed with this bulk retrieval from my Faiss index in the most efficient manner.

**Comment by rom1504** [comment]
8M samples is quite small.
What about doing all of this in memory? do a index.search then use pandas indexing to get the metadata result
you can check clip-retrieval code for an example

**Comment by victor-paltz** [comment]
Hello!
Converting parquet files to numpy to use the created Faiss index is a good solution, especially for 250K query embeddings that would take only 500MB in RAM if you loaded them all at once.

That's what we do in Autofaiss code, you can get some inspiration from there :)
Basically, you can use `embedding reader` library (https://github.com/rom1504/embedding-reader) to automatically get an iterator on your parquet embeddings with one line of code, and then use it as input in your `index.search()` function.

**Comment by ivishalanand** [comment]
@victor-paltz  for 250k query embedding, it would work,  But 

I have 2 questions 
1. What about if I have like 3-5 million query embeddings? When it becomes difficult to load the embeddings in memory?

> Basically, you can use embedding reader library (https://github.com/rom1504/embedding-reader) to automatically get an iterator on your parquet embeddings with one line of code, and then use it as input in your index.search() function

2. regarding the above do you mean this?
```
from embedding_reader import EmbeddingReader

embedding_reader = EmbeddingReader(embeddings_folder="hdfs://root/user/toto/embeddings", file_format="parquet")

for emb, _ in embedding_reader(batch_size=batch_size, start=0, end=embedding_reader.count):
    # Perform the search for the current batch of embeddings
    distances, indices = index.search(emb, top_k=20)
    # ......
```

**Comment by rom1504** [comment]
2. Yes

3. There is two main ways

- start N http servers that can serve search requests and call them with a method such as point 2
- directly load the knn index with pyspark, once per executor

You can check the "scale to 1T" guide in faiss doc, it mentions that kind of topic
