### ISSUE TITLE
Control verbosity of messages

### ISSUE THREAD

**Issue by dobraczka** [criteo/autofaiss#61]
Hi, thanks for this library, it really helps, when working with faiss! One minor problem I have is that I would like to control the verbosity of the messages, since I use this autofaiss in [my own](https://github.com/dobraczka/kiez) library. The simplest way to do that would probably through the use of python's logging module.

Is there anything planned in that regard?

**Comment by rom1504** [comment]
Hi, indeed that's a good point!
If you were to do a pull request using the logging lib instead of prints it would be appreciated!

**Comment by rom1504** [comment]
now done, thanks
