### ISSUE TITLE
Fix potential out of disk problem when producing N indices

### ISSUE THREAD

**Issue by hitchhicker** [criteo/autofaiss#91]
When we produce N indices (with `nb_indices_to_keep` larger than 1), within the function of `optimize_and_measure_indices`, we download N indices from remote in one shot (see [here](https://github.com/criteo/autofaiss/blob/6a03650ff7dda47359f6e7d1f731829dac346a66/autofaiss/external/optimize.py#L482-L484)), if the machine running autofaiss has limited disk space, it would fail due to `No space left` error.

**Comment by rom1504** [comment]
Probably possible to get only one index at a time and compute the results for this index then delete it

**Comment by hitchhicker** [comment]
Yeah, that's the most simple and safe approach.

**Comment by rom1504** [comment]
fixed now
